// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Handlebars = require("handlebars");

function init(param) {
  Handlebars.registerHelper("capitalize", (function (aString) {
          if (aString !== undefined) {
            if (aString === "") {
              return Js_exn.raiseError("can't capitalize an empty argument");
            } else {
              return aString.charAt(0).toUpperCase() + aString.substring(1);
            }
          } else {
            return Js_exn.raiseError("can't capitalize an undefined argument");
          }
        }));
  return Handlebars.registerHelper("decapitalize", (function (aString) {
                if (aString !== undefined) {
                  if (aString === "") {
                    return Js_exn.raiseError("can't decapitalize an empty argument");
                  } else {
                    return aString.charAt(0).toLowerCase() + aString.substring(1);
                  }
                } else {
                  return Js_exn.raiseError("can't decapitalize an undefined argument");
                }
              }));
}

function compile(data, template) {
  var moduleTemplate = Handlebars.compile(template, {
        strict: true,
        noEscape: true
      });
  return moduleTemplate(data);
}

exports.init = init;
exports.compile = compile;
/* handlebars Not a pure module */
