// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var PackageJson = require("../../package.json");

var $$package = PackageJson;

function constructData(moduleBase, moduleName, template, baseData) {
  baseData.moduleBase = moduleBase;
  baseData.template = template;
  baseData.moduleName = moduleName;
  baseData.version = $$package.version;
  return baseData;
}

function getOrThrow(option, string) {
  if (option !== undefined) {
    return Caml_option.valFromOption(option);
  } else {
    return Js_exn.raiseError(string);
  }
}

exports.$$package = $$package;
exports.constructData = constructData;
exports.getOrThrow = getOrThrow;
/* package Not a pure module */
