// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("rescript/lib/js/js_exn.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function constructData(moduleBase, moduleName, template, baseData) {
  baseData.moduleBase = moduleBase;
  baseData.template = template;
  baseData.moduleName = moduleName;
  return baseData;
}

function getOrThrow(option, string) {
  if (option !== undefined) {
    return Caml_option.valFromOption(option);
  } else {
    return Js_exn.raiseError(string);
  }
}

exports.constructData = constructData;
exports.getOrThrow = getOrThrow;
/* No side effect */
